# Generated by Django 5.0.2 on 2024-02-27 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('usertype', models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor')], max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('shopname', models.CharField(blank=True, max_length=100, null=True)),
                ('ssn', models.CharField(blank=True, default=0, max_length=100)),
                ('rate', models.IntegerField(blank=True, default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
