# Generated by Django 5.0.2 on 2024-02-29 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ssn',
            field=models.CharField(blank=True, max_length=14, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_ssn', message='SSN must be 14 numeric digits', regex='^[0-9]{14}$')]),
        ),
    ]
