# Generated by Django 5.0.2 on 2024-02-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ssn',
            field=models.IntegerField(blank=True),
        ),
    ]
