# Generated by Django 5.0.2 on 2024-02-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_ssn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ssn',
            field=models.CharField(blank=True),
        ),
    ]
