# Generated by Django 5.0.2 on 2024-03-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor')], null=True),
        ),
    ]
