# Generated by Django 5.0.2 on 2024-03-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imageUrl',
            field=models.URLField(null=True),
        ),
    ]
