# Generated by Django 5.0.1 on 2024-02-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prise', models.IntegerField()),
                ('Categories', models.CharField(choices=[('KIA', 'KIA'), ('BMW', 'BMW'), ('BYD', 'BYD'), ('GEELY', 'GEELY')], max_length=100, null=True)),
            ],
        ),
    ]
