# Generated by Django 5.0.3 on 2024-03-24 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
    ]
