# Generated by Django 5.0.2 on 2024-03-24 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_shop_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shop_name',
        ),
    ]
