# Generated by Django 5.0.2 on 2024-03-03 20:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prodImageCover',
            field=models.ImageField(default='static/covers/no-product.png', upload_to='product/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Product Image Cover'),
        ),
    ]
