# Generated by Django 5.0.2 on 2024-03-10 21:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prodFavorite',
            field=models.ManyToManyField(blank=True, related_name='Favorite', to=settings.AUTH_USER_MODEL, verbose_name='favorite'),
        ),
    ]
