# Generated by Django 5.0.3 on 2024-03-12 19:38

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='prodImageProduct',
            new_name='prodImgsForProduct',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='prodImage',
        ),
        migrations.AddField(
            model_name='product',
            name='prodFavorite',
            field=models.ManyToManyField(blank=True, related_name='Favorite', to=settings.AUTH_USER_MODEL, verbose_name='favorite'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='prodImages',
            field=models.FileField(default=1, upload_to='product/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Product Images'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rateRating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0, 'Rating must be at least 0.0'), django.core.validators.MaxValueValidator(5.0, 'Rating cannot exceed 5.0')], verbose_name='Rate')),
                ('rateSubject', models.CharField(max_length=2000)),
                ('rateReview', models.TextField(blank=True, max_length=2000)),
                ('rateCreatedDate', models.DateTimeField(default=datetime.datetime.now)),
                ('rateCustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rateProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
