# Generated by Django 5.0.2 on 2024-03-12 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='prodImages',
            new_name='prodImage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prodFavorite',
        ),
        migrations.AddField(
            model_name='product',
            name='prodImages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productimage'),
        ),
    ]
