# Generated by Django 5.0.2 on 2024-03-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_prodimages_productimage_prodimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prodImages',
        ),
        migrations.AddField(
            model_name='product',
            name='prodUploadedImages',
            field=models.ManyToManyField(blank=True, to='product.productimage'),
        ),
    ]
