# Generated by Django 5.0.3 on 2024-03-12 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_prodimageproduct_productimage_prodimgsforproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prodOnSale',
        ),
    ]
