# Generated by Django 5.0.3 on 2024-03-12 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_prodonsale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prodFavorite',
        ),
    ]
