# Generated by Django 5.0.2 on 2024-03-12 22:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_produploadedimages_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prodFavorite',
            field=models.ManyToManyField(blank=True, related_name='Favorite', to=settings.AUTH_USER_MODEL, verbose_name='favorite'),
        ),
    ]
